#include "PostgresAdminAuditRepository.h"

#include <algorithm>
#include <libpq-fe.h>
#include <mutex>
#include <stdexcept>

PostgresAdminAuditRepository::PostgresAdminAuditRepository(PostgresConnection& connection)
    : db(connection)
{
    ensureTable();
}

void PostgresAdminAuditRepository::ensureTable()
{
    std::lock_guard<std::mutex> lock(db.mutex());

    PGresult* res = PQexec(
        db.get(),
        "CREATE TABLE IF NOT EXISTS admin_audit_log ("
        "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
        "admin_id INTEGER REFERENCES users(id) ON DELETE SET NULL,"
        "action TEXT NOT NULL,"
        "target_type TEXT NOT NULL,"
        "target_id INTEGER,"
        "details TEXT NOT NULL,"
        "created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP"
        ")");

    if (PQresultStatus(res) != PGRES_COMMAND_OK) {
        std::string error = PQerrorMessage(db.get());
        PQclear(res);
        throw std::runtime_error("Failed to ensure admin audit table: " + error);
    }

    PQclear(res);
}

void PostgresAdminAuditRepository::recordEvent(
    int adminId,
    const std::string& action,
    const std::string& targetType,
    int targetId,
    const std::string& details)
{
    std::lock_guard<std::mutex> lock(db.mutex());

    const std::string adminIdValue = std::to_string(adminId);
    const std::string targetIdValue = targetId >= 0 ? std::to_string(targetId) : std::string();
    const char* params[] = {
        adminIdValue.c_str(),
        action.c_str(),
        targetType.c_str(),
        targetId >= 0 ? targetIdValue.c_str() : nullptr,
        details.c_str()
    };

    PGresult* res = PQexecParams(
        db.get(),
        "INSERT INTO admin_audit_log(admin_id, action, target_type, target_id, details) "
        "VALUES($1, $2, $3, $4, $5)",
        5,
        nullptr,
        params,
        nullptr,
        nullptr,
        0);

    if (PQresultStatus(res) != PGRES_COMMAND_OK) {
        std::string error = PQerrorMessage(db.get());
        PQclear(res);
        throw std::runtime_error("Failed to record admin audit event: " + error);
    }

    PQclear(res);
}

std::vector<AdminAuditEvent> PostgresAdminAuditRepository::getRecentEvents(int limit)
{
    std::lock_guard<std::mutex> lock(db.mutex());

    const int safeLimit = std::clamp(limit, 1, 50);
    const std::string limitValue = std::to_string(safeLimit);
    const char* params[] = {limitValue.c_str()};

    PGresult* res = PQexecParams(
        db.get(),
        "SELECT l.id, COALESCE(l.admin_id, -1), COALESCE(u.login, 'deleted_admin'), "
        "l.action, l.target_type, COALESCE(l.target_id, -1), l.details, "
        "to_char(l.created_at, 'DD.MM.YYYY HH24:MI') "
        "FROM admin_audit_log l "
        "LEFT JOIN users u ON u.id = l.admin_id "
        "ORDER BY l.created_at DESC, l.id DESC "
        "LIMIT $1",
        1,
        nullptr,
        params,
        nullptr,
        nullptr,
        0);

    if (PQresultStatus(res) != PGRES_TUPLES_OK) {
        std::string error = PQerrorMessage(db.get());
        PQclear(res);
        throw std::runtime_error("Failed to get admin audit events: " + error);
    }

    std::vector<AdminAuditEvent> events;
    const int rows = PQntuples(res);
    events.reserve(rows);

    for (int i = 0; i < rows; ++i) {
        AdminAuditEvent event;
        event.id = std::stoi(PQgetvalue(res, i, 0));
        event.adminId = std::stoi(PQgetvalue(res, i, 1));
        event.adminLogin = PQgetvalue(res, i, 2);
        event.action = PQgetvalue(res, i, 3);
        event.targetType = PQgetvalue(res, i, 4);
        event.targetId = std::stoi(PQgetvalue(res, i, 5));
        event.details = PQgetvalue(res, i, 6);
        event.createdAt = PQgetvalue(res, i, 7);
        events.push_back(event);
    }

    PQclear(res);
    return events;
}
