CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('Student', 'Teacher', 'Admin'))
);

CREATE TABLE IF NOT EXISTS courses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    teacher_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS enrollments (
    student_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    course_id INTEGER NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    PRIMARY KEY (student_id, course_id)
);

CREATE TABLE IF NOT EXISTS lessons (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id INTEGER NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    content TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS materials (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_id INTEGER NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    type TEXT NOT NULL,
    content TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS tests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id INTEGER NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    title TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS questions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_id INTEGER NOT NULL REFERENCES tests(id) ON DELETE CASCADE,
    text TEXT NOT NULL,
    correct_answer_id INTEGER
);

CREATE TABLE IF NOT EXISTS answers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id INTEGER NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
    text TEXT NOT NULL
);

ALTER TABLE questions
    ADD CONSTRAINT questions_correct_answer_fk
    FOREIGN KEY (correct_answer_id)
    REFERENCES answers(id)
    DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS attempts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    test_id INTEGER NOT NULL REFERENCES tests(id) ON DELETE CASCADE,
    score INTEGER NOT NULL,
    total INTEGER NOT NULL,
    percentage DOUBLE PRECISION NOT NULL,
    passed BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO users (id, login, password_hash, role) VALUES
    (1, 'teacher1', '3766126602758038891', 'Teacher'),
    (2, 'student_demo', '2992457363794458960', 'Student'),
    (3, 'admin', '17197393981645110028', 'Admin')
ON CONFLICT (login) DO UPDATE SET
    password_hash = EXCLUDED.password_hash,
    role = EXCLUDED.role;

INSERT INTO courses (id, title, description, teacher_id) VALUES
    (1, 'C++ Basics', 'Intro to C++ syntax, functions and memory basics', 1),
    (2, 'OOP Design', 'Classes, inheritance and basic design principles', 1),
    (3, 'Databases', 'SQL and PostgreSQL fundamentals', 1)
ON CONFLICT (id) DO NOTHING;

INSERT INTO enrollments (student_id, course_id) VALUES
    (2, 1)
ON CONFLICT DO NOTHING;

INSERT INTO lessons (id, course_id, title, content) VALUES
    (1, 1, 'Variables and Types', 'C++ variables, primitive types and declarations.'),
    (2, 1, 'Functions', 'Function declaration, definition and calls.'),
    (3, 2, 'Classes', 'Basic class syntax and object creation.'),
    (4, 3, 'SQL Select', 'Reading data from relational tables.')
ON CONFLICT (id) DO NOTHING;

INSERT INTO materials (id, lesson_id, title, type, content) VALUES
    (1, 1, 'Variables notes', 'text', 'Use int, double, bool and std::string for basic data.'),
    (2, 2, 'Functions notes', 'text', 'A function has return type, name, parameters and body.'),
    (3, 3, 'Classes notes', 'text', 'A class groups fields and methods.'),
    (4, 4, 'SELECT notes', 'text', 'SELECT columns FROM table WHERE condition.')
ON CONFLICT (id) DO NOTHING;

INSERT INTO tests (id, course_id, title) VALUES
    (1, 1, 'C++ Basic Test'),
    (2, 1, 'Functions Test'),
    (3, 2, 'OOP Test')
ON CONFLICT (id) DO NOTHING;

INSERT INTO questions (id, test_id, text, correct_answer_id) VALUES
    (1, 1, 'Which type stores true or false?', NULL),
    (2, 1, 'Which header is commonly used for std::string?', NULL),
    (3, 2, 'What does a function return type describe?', NULL)
ON CONFLICT (id) DO NOTHING;

INSERT INTO answers (id, question_id, text) VALUES
    (1, 1, 'int'),
    (2, 1, 'bool'),
    (3, 1, 'double'),
    (4, 2, '<string>'),
    (5, 2, '<vector>'),
    (6, 2, '<iostream>'),
    (7, 3, 'The value type returned by the function'),
    (8, 3, 'The function name'),
    (9, 3, 'The number of parameters')
ON CONFLICT (id) DO NOTHING;

UPDATE questions SET correct_answer_id = 2 WHERE id = 1;
UPDATE questions SET correct_answer_id = 4 WHERE id = 2;
UPDATE questions SET correct_answer_id = 7 WHERE id = 3;

SELECT setval(pg_get_serial_sequence('users', 'id'), COALESCE((SELECT MAX(id) FROM users), 1));
SELECT setval(pg_get_serial_sequence('courses', 'id'), COALESCE((SELECT MAX(id) FROM courses), 1));
SELECT setval(pg_get_serial_sequence('lessons', 'id'), COALESCE((SELECT MAX(id) FROM lessons), 1));
SELECT setval(pg_get_serial_sequence('materials', 'id'), COALESCE((SELECT MAX(id) FROM materials), 1));
SELECT setval(pg_get_serial_sequence('tests', 'id'), COALESCE((SELECT MAX(id) FROM tests), 1));
SELECT setval(pg_get_serial_sequence('questions', 'id'), COALESCE((SELECT MAX(id) FROM questions), 1));
SELECT setval(pg_get_serial_sequence('answers', 'id'), COALESCE((SELECT MAX(id) FROM answers), 1));
SELECT setval(pg_get_serial_sequence('attempts', 'id'), COALESCE((SELECT MAX(id) FROM attempts), 1));
