CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('Student', 'Teacher', 'Admin')),
    first_name TEXT NOT NULL DEFAULT '',
    last_name TEXT NOT NULL DEFAULT '',
    group_name TEXT NOT NULL DEFAULT '',
    email TEXT NOT NULL DEFAULT '',
    phone TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS courses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    teacher_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS enrollments (
    student_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    course_id INTEGER NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    PRIMARY KEY (student_id, course_id)
);

CREATE TABLE IF NOT EXISTS lessons (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id INTEGER NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    content TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS materials (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_id INTEGER NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    type TEXT NOT NULL,
    content TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS lesson_progress (
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    lesson_id INTEGER NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,
    completed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, lesson_id)
);

CREATE TABLE IF NOT EXISTS tests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id INTEGER NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'closed')),
    deadline_at TIMESTAMP NULL,
    max_attempts INTEGER NOT NULL DEFAULT 0 CHECK (max_attempts >= 0),
    time_limit_minutes INTEGER NOT NULL DEFAULT 30 CHECK (time_limit_minutes BETWEEN 1 AND 300)
);

CREATE TABLE IF NOT EXISTS questions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_id INTEGER NOT NULL REFERENCES tests(id) ON DELETE CASCADE,
    text TEXT NOT NULL,
    correct_answer_id INTEGER
);

CREATE TABLE IF NOT EXISTS answers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id INTEGER NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
    text TEXT NOT NULL
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'questions_correct_answer_fk'
    ) THEN
        ALTER TABLE questions
            ADD CONSTRAINT questions_correct_answer_fk
            FOREIGN KEY (correct_answer_id)
            REFERENCES answers(id)
            DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS attempts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    test_id INTEGER NOT NULL REFERENCES tests(id) ON DELETE CASCADE,
    score INTEGER NOT NULL,
    total INTEGER NOT NULL,
    percentage DOUBLE PRECISION NOT NULL,
    passed BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS admin_audit_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    action TEXT NOT NULL,
    target_type TEXT NOT NULL,
    target_id INTEGER,
    details TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS groups (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

ALTER TABLE users ADD COLUMN IF NOT EXISTS first_name TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_name TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS group_name TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS email TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone TEXT NOT NULL DEFAULT '';
ALTER TABLE tests ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'active';
ALTER TABLE tests ADD COLUMN IF NOT EXISTS deadline_at TIMESTAMP NULL;
ALTER TABLE tests ADD COLUMN IF NOT EXISTS max_attempts INTEGER NOT NULL DEFAULT 0;
ALTER TABLE tests ADD COLUMN IF NOT EXISTS time_limit_minutes INTEGER NOT NULL DEFAULT 30;
ALTER TABLE tests DROP CONSTRAINT IF EXISTS tests_status_check;
ALTER TABLE tests ADD CONSTRAINT tests_status_check CHECK (status IN ('active', 'closed'));
ALTER TABLE tests DROP CONSTRAINT IF EXISTS tests_max_attempts_check;
ALTER TABLE tests ADD CONSTRAINT tests_max_attempts_check CHECK (max_attempts >= 0);
ALTER TABLE tests DROP CONSTRAINT IF EXISTS tests_time_limit_minutes_check;
ALTER TABLE tests ADD CONSTRAINT tests_time_limit_minutes_check CHECK (time_limit_minutes BETWEEN 1 AND 300);

INSERT INTO groups (name) VALUES
    ('ИВТ-401'),
    ('ИВТ-402'),
    ('ИВТ-403'),
    ('ПИ-301'),
    ('ПИ-302')
ON CONFLICT (name) DO NOTHING;

INSERT INTO users (id, login, password_hash, role, first_name, last_name, group_name, email, phone) VALUES
    (1, 'teacher1', '3766126602758038891', 'Teacher', 'Иван', 'Петров', 'Кафедра программной инженерии', 'ivan.petrov@lms.local', '+7 900 111-22-33'),
    (2, 'student_demo', '2992457363794458960', 'Student', 'Даниил', 'Дружинин', 'ИВТ-401', 'daniil.druzhinin@student.lms.local', '+7 900 222-33-44'),
    (3, 'admin', '17197393981645110028', 'Admin', 'Мария', 'Соколова', 'Администрация LMS', 'admin@lms.local', '+7 900 333-44-55'),
    (101, 'student_anna', '2992457363794458960', 'Student', 'Анна', 'Иванова', 'ИВТ-401', 'anna.ivanova@student.lms.local', '+7 900 444-55-66'),
    (102, 'student_oleg', '2992457363794458960', 'Student', 'Олег', 'Смирнов', 'ИВТ-402', 'oleg.smirnov@student.lms.local', '+7 900 555-66-77'),
    (103, 'teacher2', '3766126602758038891', 'Teacher', 'Елена', 'Морозова', 'Кафедра информационных систем', 'elena.morozova@lms.local', '+7 900 666-77-88')
ON CONFLICT (login) DO UPDATE SET
    password_hash = EXCLUDED.password_hash,
    role = EXCLUDED.role,
    first_name = EXCLUDED.first_name,
    last_name = EXCLUDED.last_name,
    group_name = EXCLUDED.group_name,
    email = EXCLUDED.email,
    phone = EXCLUDED.phone;

INSERT INTO courses (id, title, description, teacher_id) VALUES
    (1, 'C++ Basics', 'Базовый курс по современному C++: типы данных, функции, память, строки и безопасная работа с кодом.', 1),
    (2, 'Object-Oriented Design', 'Проектирование классов, инкапсуляция, наследование и практические принципы ООП на примерах.', 1),
    (3, 'Databases and SQL', 'Основы реляционных баз данных: SELECT, связи таблиц, фильтрация, агрегаты и PostgreSQL.', 1),
    (101, 'Web Backend Fundamentals', 'Практический курс по проектированию REST API, обработке JSON, авторизации и работе backend-сервиса с базой данных.', 103)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    teacher_id = EXCLUDED.teacher_id;

INSERT INTO enrollments (student_id, course_id) VALUES
    (2, 1),
    (2, 2),
    (2, 101),
    (101, 1),
    (101, 3),
    (102, 3),
    (102, 101)
ON CONFLICT DO NOTHING;

INSERT INTO lessons (id, course_id, title, content) VALUES
    (1, 1, 'Урок 1. Переменные и типы данных', 'В C++ переменная связывает имя с областью памяти, где хранится значение определённого типа. Тип определяет, какие значения допустимы и какие операции можно выполнять.\n\nБазовые типы:\n- int для целых чисел;\n- double для вещественных чисел;\n- bool для логических значений;\n- char для одного символа;\n- std::string для строк.\n\nПример:\nint age = 20;\ndouble rating = 4.8;\nbool passed = true;\nstd::string name = "Student";\n\nХорошая практика: выбирайте тип по смыслу данных, задавайте понятные имена и инициализируйте переменные сразу при объявлении.'),
    (2, 1, 'Урок 2. Функции и разбиение программы', 'Функция помогает разделить программу на небольшие понятные блоки. У функции есть тип возвращаемого значения, имя, параметры и тело.\n\nПример:\nint sum(int a, int b) {\n    return a + b;\n}\n\nПочему функции важны:\n- уменьшают дублирование кода;\n- позволяют тестировать отдельные части программы;\n- делают код читаемым;\n- помогают выделить бизнес-логику.\n\nЕсли функция ничего не возвращает, используется тип void. Для входных данных лучше выбирать параметры с понятными именами.'),
    (3, 1, 'Урок 3. Строки и стандартная библиотека', 'Для работы со строками в C++ обычно используется std::string из заголовочного файла <string>. Строки можно объединять, сравнивать, передавать в функции и читать из ввода.\n\nПример:\n#include <string>\n\nstd::string firstName = "Daniil";\nstd::string greeting = "Hello, " + firstName;\n\nСтандартная библиотека C++ экономит время: в ней уже есть контейнеры, алгоритмы, строки и инструменты ввода-вывода. На практике важно не писать всё с нуля, а грамотно использовать готовые компоненты.'),
    (4, 2, 'Урок 1. Классы и объекты', 'Класс описывает структуру объекта: его данные и поведение. Объект — это конкретный экземпляр класса.\n\nПример:\nclass Course {\npublic:\n    std::string title;\n\n    void printTitle() const {\n        std::cout << title;\n    }\n};\n\nКласс помогает объединить связанные данные и операции. Это делает программу ближе к предметной области: Course, User, Test, Lesson выглядят естественно для LMS.'),
    (5, 2, 'Урок 2. Инкапсуляция', 'Инкапсуляция ограничивает прямой доступ к внутреннему состоянию объекта. Обычно поля делают private, а безопасные операции — public.\n\nЗачем это нужно:\n- объект сам контролирует корректность данных;\n- внешний код меньше зависит от внутренней реализации;\n- проще менять класс без поломки всей системы.\n\nВ LMS примером инкапсуляции может быть сервис попыток теста: внешний код отправляет ответы, а сервис сам считает балл, процент и статус прохождения.'),
    (6, 3, 'Урок 1. SELECT и фильтрация', 'SELECT используется для чтения данных из таблиц. Базовая форма запроса:\n\nSELECT column_name FROM table_name WHERE condition;\n\nПримеры:\nSELECT title FROM courses;\nSELECT login FROM users WHERE role = ''Student'';\n\nWHERE позволяет отфильтровать строки. ORDER BY сортирует результат. LIMIT ограничивает количество строк. Эти операции часто используются в API, когда клиент запрашивает списки курсов, пользователей или попыток.'),
    (7, 3, 'Урок 2. Связи таблиц', 'Реляционная база данных хранит сущности в отдельных таблицах, а связи между ними задаются внешними ключами.\n\nПример LMS:\n- users хранит пользователей;\n- courses хранит курсы;\n- enrollments связывает студентов и курсы;\n- lessons привязаны к courses;\n- tests привязаны к courses.\n\nJOIN позволяет получить данные из нескольких таблиц сразу, например список курсов вместе с ФИО преподавателя.'),
    (101, 3, 'Урок 3. Агрегация и группировка', 'Агрегирующие функции позволяют получать сводные значения по набору строк.\n\nЧастые функции:\n- COUNT считает количество строк;\n- AVG находит среднее значение;\n- MIN и MAX определяют границы;\n- SUM суммирует значения.\n\nGROUP BY группирует строки по выбранному признаку. В LMS такой подход используется, например, для расчёта среднего результата тестов по группе студентов.'),
    (102, 101, 'Урок 1. REST API и маршруты', 'REST API описывает набор маршрутов, через которые клиентское приложение обращается к серверу.\n\nПример маршрутов LMS:\nGET /api/courses — получить список курсов;\nPOST /api/auth/login — выполнить вход;\nPOST /api/tests/{id}/submit — отправить ответы на тест.\n\nХороший API должен быть предсказуемым: URL отражает сущность, HTTP-метод отражает действие, а ответ возвращается в понятном JSON-формате.'),
    (103, 101, 'Урок 2. JSON и валидация входных данных', 'JSON используется для передачи структурированных данных между Qt-клиентом и backend-сервисом.\n\nПример тела запроса:\n{\n  "title": "New Course",\n  "description": "Course description"\n}\n\nНа сервере важно проверять обязательные поля, типы данных и права пользователя. Даже если клиент уже проверил форму, backend не должен доверять входным данным без валидации.'),
    (104, 101, 'Урок 3. Авторизация и роли', 'Авторизация определяет, какие действия доступны пользователю после входа.\n\nВ LMS используются роли:\n- Student читает материалы и проходит тесты;\n- Teacher управляет своими курсами;\n- Admin управляет пользователями, группами и общей структурой.\n\nРолевые проверки защищают данные: студент не должен редактировать курс, а преподаватель не должен управлять чужими пользователями.')
ON CONFLICT (id) DO UPDATE SET
    course_id = EXCLUDED.course_id,
    title = EXCLUDED.title,
    content = EXCLUDED.content;

INSERT INTO materials (id, lesson_id, title, type, content) VALUES
    (1, 1, 'Конспект: выбор типа данных', 'text', 'Краткая памятка:\n1. int — счётчики, идентификаторы, количество.\n2. double — дробные значения и измерения.\n3. bool — флаги состояния.\n4. std::string — текстовые данные.\n\nЕсли значение не должно меняться, используйте const. Это делает намерение кода очевидным.'),
    (2, 1, 'Справочник cppreference: fundamental types', 'link', 'https://en.cppreference.com/w/cpp/language/types'),
    (3, 2, 'Практика: разбиение программы на функции', 'text', 'Задание: напишите функции calculateAverage, isPassed и formatStudentResult. Главная функция должна только читать данные, вызывать эти функции и выводить результат.'),
    (4, 2, 'Видео: функции в C++', 'video', 'https://www.youtube.com/results?search_query=c%2B%2B+functions+tutorial'),
    (5, 3, 'Справочник: std::string', 'link', 'https://en.cppreference.com/w/cpp/string/basic_string'),
    (6, 4, 'Шаблон класса Course', 'text', 'Минимальная структура класса Course:\n- поле title;\n- поле description;\n- метод printSummary();\n- конструктор с параметрами.\n\nДополнительно: попробуйте скрыть поля через private и добавить getters.'),
    (7, 5, 'Инкапсуляция на примере LMS', 'text', 'В хорошей архитектуре UI не должен сам считать результат теста. Qt-клиент отправляет ответы, backend проверяет их через сервис и возвращает готовый результат. Это снижает риск ошибок и делает систему надёжнее.'),
    (8, 6, 'Памятка SQL SELECT', 'text', 'SELECT title, description FROM courses ORDER BY id;\nSELECT login, role FROM users WHERE role = ''Teacher'';\nSELECT * FROM attempts WHERE percentage >= 70;'),
    (9, 7, 'PostgreSQL JOIN documentation', 'link', 'https://www.postgresql.org/docs/current/tutorial-join.html'),
    (101, 101, 'Практика: GROUP BY для журнала результатов', 'text', 'Задание: составьте запрос, который выводит средний процент прохождения по каждому тесту. Используйте attempts, tests, AVG и GROUP BY.'),
    (102, 101, 'PostgreSQL aggregate functions', 'link', 'https://www.postgresql.org/docs/current/functions-aggregate.html'),
    (103, 102, 'Чек-лист проектирования endpoint', 'text', 'Перед добавлением endpoint проверьте:\n1. Какой ресурс обрабатывается.\n2. Какой HTTP-метод подходит.\n3. Какие поля обязательны.\n4. Какая роль имеет право выполнить запрос.\n5. Какие ошибки должен вернуть сервер.'),
    (104, 103, 'JSON specification overview', 'link', 'https://www.json.org/json-en.html'),
    (105, 103, 'Видео: основы JSON для backend', 'video', 'https://www.youtube.com/results?search_query=json+rest+api+tutorial'),
    (106, 104, 'Памятка по ролям LMS', 'text', 'Student: просмотр курсов, уроков, материалов и тестов.\nTeacher: создание и редактирование своих курсов, уроков, материалов, тестов.\nAdmin: пользователи, группы, общая аналитика и административные операции.')
ON CONFLICT (id) DO UPDATE SET
    lesson_id = EXCLUDED.lesson_id,
    title = EXCLUDED.title,
    type = EXCLUDED.type,
    content = EXCLUDED.content;

INSERT INTO lesson_progress (user_id, lesson_id, completed_at) VALUES
    (2, 1, CURRENT_TIMESTAMP - INTERVAL '3 days'),
    (2, 2, CURRENT_TIMESTAMP - INTERVAL '2 days'),
    (101, 1, CURRENT_TIMESTAMP - INTERVAL '1 day'),
    (102, 6, CURRENT_TIMESTAMP - INTERVAL '4 days')
ON CONFLICT (user_id, lesson_id) DO NOTHING;

INSERT INTO tests (id, course_id, title, status, deadline_at, max_attempts, time_limit_minutes) VALUES
    (1, 1, 'Контрольный тест: основы C++', 'active', CURRENT_TIMESTAMP + INTERVAL '14 days', 2, 30),
    (2, 1, 'Functions and Strings Test', 'active', CURRENT_TIMESTAMP + INTERVAL '21 days', 3, 25),
    (3, 2, 'OOP Principles Test', 'closed', NULL, 1, 20),
    (4, 1, 'Контрольный тест', 'active', CURRENT_TIMESTAMP + INTERVAL '30 days', 2, 40),
    (101, 3, 'SQL Basics Checkpoint', 'active', CURRENT_TIMESTAMP + INTERVAL '10 days', 2, 25),
    (102, 101, 'REST API Practice Test', 'active', CURRENT_TIMESTAMP + INTERVAL '18 days', 3, 35)
ON CONFLICT (id) DO UPDATE SET
    course_id = EXCLUDED.course_id,
    title = EXCLUDED.title,
    status = EXCLUDED.status,
    deadline_at = EXCLUDED.deadline_at,
    max_attempts = EXCLUDED.max_attempts,
    time_limit_minutes = EXCLUDED.time_limit_minutes;

INSERT INTO questions (id, test_id, text, correct_answer_id) VALUES
    (1, 1, 'Какой тип данных хранит значения true или false?', NULL),
    (2, 1, 'Какой заголовочный файл обычно подключают для std::string?', NULL),
    (3, 1, 'Что означает const перед переменной?', NULL),
    (4, 2, 'Что описывает тип возвращаемого значения функции?', NULL),
    (5, 2, 'Зачем программу разбивают на функции?', NULL),
    (6, 3, 'Какой модификатор доступа чаще используют для скрытия внутреннего состояния класса?', NULL),
    (7, 3, 'Что такое объект в ООП?', NULL),
    (8, 4, 'Какой тип в C++ удобно использовать для хранения логического результата проверки?', NULL),
    (9, 4, 'Что делает ключевое слово const перед локальной переменной?', NULL),
    (101, 101, 'Какой SQL-оператор используется для чтения данных из таблицы?', NULL),
    (102, 101, 'Для чего используется JOIN?', NULL),
    (103, 101, 'Какая функция считает количество строк?', NULL),
    (104, 102, 'Какой HTTP-метод обычно используют для получения списка ресурсов?', NULL),
    (105, 102, 'Что обычно передаёт клиент в теле POST-запроса к JSON API?', NULL),
    (106, 102, 'Где должна выполняться финальная проверка прав пользователя?', NULL)
ON CONFLICT (id) DO UPDATE SET
    test_id = EXCLUDED.test_id,
    text = EXCLUDED.text;

INSERT INTO answers (id, question_id, text) VALUES
    (1, 1, 'int'),
    (2, 1, 'bool'),
    (3, 1, 'double'),
    (4, 1, 'char'),
    (5, 2, '<string>'),
    (6, 2, '<vector>'),
    (7, 2, '<iostream>'),
    (8, 2, '<map>'),
    (9, 3, 'Значение нельзя изменить после инициализации'),
    (10, 3, 'Переменная становится глобальной'),
    (11, 3, 'Тип автоматически меняется во время выполнения'),
    (12, 3, 'Компилятор игнорирует эту переменную'),
    (13, 4, 'Тип значения, которое функция возвращает вызывающему коду'),
    (14, 4, 'Имя функции'),
    (15, 4, 'Количество параметров'),
    (16, 4, 'Файл, где находится функция'),
    (17, 5, 'Чтобы убрать дублирование и сделать код понятнее'),
    (18, 5, 'Чтобы программа обязательно работала медленнее'),
    (19, 5, 'Чтобы все переменные стали глобальными'),
    (20, 5, 'Чтобы не подключать заголовочные файлы'),
    (21, 6, 'private'),
    (22, 6, 'public'),
    (23, 6, 'friend'),
    (24, 6, 'static'),
    (25, 7, 'Конкретный экземпляр класса'),
    (26, 7, 'Только текстовый файл'),
    (27, 7, 'Любая SQL-таблица'),
    (28, 7, 'Оператор ветвления'),
    (29, 8, 'int'),
    (30, 8, 'bool'),
    (31, 8, 'double'),
    (32, 8, 'std::string'),
    (33, 9, 'Запрещает изменять значение после инициализации'),
    (34, 9, 'Создаёт новый поток'),
    (35, 9, 'Удаляет переменную из памяти'),
    (36, 9, 'Делает переменную глобальной'),
    (101, 101, 'SELECT'),
    (102, 101, 'INSERT'),
    (103, 101, 'DELETE'),
    (104, 101, 'ALTER'),
    (105, 102, 'Для объединения данных из связанных таблиц'),
    (106, 102, 'Для удаления всех данных'),
    (107, 102, 'Для создания роли пользователя'),
    (108, 102, 'Для запуска Docker-контейнера'),
    (109, 103, 'COUNT'),
    (110, 103, 'JOIN'),
    (111, 103, 'ORDER BY'),
    (112, 103, 'WHERE'),
    (113, 104, 'GET'),
    (114, 104, 'PATCH'),
    (115, 104, 'DELETE'),
    (116, 104, 'TRACE'),
    (117, 105, 'JSON с данными создаваемой или изменяемой сущности'),
    (118, 105, 'Скриншот интерфейса'),
    (119, 105, 'Пароль базы данных в открытом виде'),
    (120, 105, 'Скомпилированный бинарный файл Qt'),
    (121, 106, 'На backend-сервере'),
    (122, 106, 'Только в интерфейсе Qt'),
    (123, 106, 'Только в README'),
    (124, 106, 'В браузерной истории пользователя')
ON CONFLICT (id) DO UPDATE SET
    question_id = EXCLUDED.question_id,
    text = EXCLUDED.text;

UPDATE questions SET correct_answer_id = 2 WHERE id = 1;
UPDATE questions SET correct_answer_id = 5 WHERE id = 2;
UPDATE questions SET correct_answer_id = 9 WHERE id = 3;
UPDATE questions SET correct_answer_id = 13 WHERE id = 4;
UPDATE questions SET correct_answer_id = 17 WHERE id = 5;
UPDATE questions SET correct_answer_id = 21 WHERE id = 6;
UPDATE questions SET correct_answer_id = 25 WHERE id = 7;
UPDATE questions SET correct_answer_id = 30 WHERE id = 8;
UPDATE questions SET correct_answer_id = 33 WHERE id = 9;
UPDATE questions SET correct_answer_id = 101 WHERE id = 101;
UPDATE questions SET correct_answer_id = 105 WHERE id = 102;
UPDATE questions SET correct_answer_id = 109 WHERE id = 103;
UPDATE questions SET correct_answer_id = 113 WHERE id = 104;
UPDATE questions SET correct_answer_id = 117 WHERE id = 105;
UPDATE questions SET correct_answer_id = 121 WHERE id = 106;

INSERT INTO attempts (id, user_id, test_id, score, total, percentage, passed, created_at) VALUES
    (1, 2, 1, 2, 3, 66.7, true, CURRENT_TIMESTAMP - INTERVAL '3 days'),
    (2, 2, 2, 2, 2, 100.0, true, CURRENT_TIMESTAMP - INTERVAL '1 day'),
    (101, 101, 1, 3, 3, 100.0, true, CURRENT_TIMESTAMP - INTERVAL '2 days'),
    (102, 102, 101, 2, 3, 66.7, true, CURRENT_TIMESTAMP - INTERVAL '5 hours'),
    (103, 2, 102, 2, 3, 66.7, true, CURRENT_TIMESTAMP - INTERVAL '6 hours'),
    (104, 102, 102, 3, 3, 100.0, true, CURRENT_TIMESTAMP - INTERVAL '2 hours')
ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('users', 'id'), COALESCE((SELECT MAX(id) FROM users), 1));
SELECT setval(pg_get_serial_sequence('courses', 'id'), COALESCE((SELECT MAX(id) FROM courses), 1));
SELECT setval(pg_get_serial_sequence('lessons', 'id'), COALESCE((SELECT MAX(id) FROM lessons), 1));
SELECT setval(pg_get_serial_sequence('materials', 'id'), COALESCE((SELECT MAX(id) FROM materials), 1));
SELECT setval(pg_get_serial_sequence('tests', 'id'), COALESCE((SELECT MAX(id) FROM tests), 1));
SELECT setval(pg_get_serial_sequence('questions', 'id'), COALESCE((SELECT MAX(id) FROM questions), 1));
SELECT setval(pg_get_serial_sequence('answers', 'id'), COALESCE((SELECT MAX(id) FROM answers), 1));
SELECT setval(pg_get_serial_sequence('attempts', 'id'), COALESCE((SELECT MAX(id) FROM attempts), 1));
SELECT setval(pg_get_serial_sequence('admin_audit_log', 'id'), COALESCE((SELECT MAX(id) FROM admin_audit_log), 1));
SELECT setval(pg_get_serial_sequence('groups', 'id'), COALESCE((SELECT MAX(id) FROM groups), 1));
