CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('Student', 'Teacher', 'Admin')),
    first_name TEXT NOT NULL DEFAULT '',
    last_name TEXT NOT NULL DEFAULT '',
    group_name TEXT NOT NULL DEFAULT '',
    email TEXT NOT NULL DEFAULT '',
    phone TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS courses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    teacher_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS enrollments (
    student_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    course_id INTEGER NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    PRIMARY KEY (student_id, course_id)
);

CREATE TABLE IF NOT EXISTS lessons (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id INTEGER NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    content TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS materials (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_id INTEGER NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    type TEXT NOT NULL,
    content TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS lesson_progress (
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    lesson_id INTEGER NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,
    completed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, lesson_id)
);

CREATE TABLE IF NOT EXISTS tests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id INTEGER NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    title TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS questions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_id INTEGER NOT NULL REFERENCES tests(id) ON DELETE CASCADE,
    text TEXT NOT NULL,
    correct_answer_id INTEGER
);

CREATE TABLE IF NOT EXISTS answers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id INTEGER NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
    text TEXT NOT NULL
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'questions_correct_answer_fk'
    ) THEN
        ALTER TABLE questions
            ADD CONSTRAINT questions_correct_answer_fk
            FOREIGN KEY (correct_answer_id)
            REFERENCES answers(id)
            DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS attempts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    test_id INTEGER NOT NULL REFERENCES tests(id) ON DELETE CASCADE,
    score INTEGER NOT NULL,
    total INTEGER NOT NULL,
    percentage DOUBLE PRECISION NOT NULL,
    passed BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS admin_audit_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    action TEXT NOT NULL,
    target_type TEXT NOT NULL,
    target_id INTEGER,
    details TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE users ADD COLUMN IF NOT EXISTS first_name TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_name TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS group_name TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS email TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone TEXT NOT NULL DEFAULT '';

INSERT INTO users (id, login, password_hash, role, first_name, last_name, group_name, email, phone) VALUES
    (1, 'teacher1', '3766126602758038891', 'Teacher', 'Иван', 'Петров', 'Кафедра программной инженерии', 'ivan.petrov@lms.local', '+7 900 111-22-33'),
    (2, 'student_demo', '2992457363794458960', 'Student', 'Даниил', 'Дружинин', 'ИВТ-401', 'daniil.druzhinin@student.lms.local', '+7 900 222-33-44'),
    (3, 'admin', '17197393981645110028', 'Admin', 'Мария', 'Соколова', 'Администрация LMS', 'admin@lms.local', '+7 900 333-44-55')
ON CONFLICT (login) DO UPDATE SET
    password_hash = EXCLUDED.password_hash,
    role = EXCLUDED.role,
    first_name = EXCLUDED.first_name,
    last_name = EXCLUDED.last_name,
    group_name = EXCLUDED.group_name,
    email = EXCLUDED.email,
    phone = EXCLUDED.phone;

INSERT INTO courses (id, title, description, teacher_id) VALUES
    (1, 'C++ Basics', 'Базовый курс по современному C++: типы данных, функции, память, строки и безопасная работа с кодом.', 1),
    (2, 'Object-Oriented Design', 'Проектирование классов, инкапсуляция, наследование и практические принципы ООП на примерах.', 1),
    (3, 'Databases and SQL', 'Основы реляционных баз данных: SELECT, связи таблиц, фильтрация, агрегаты и PostgreSQL.', 1)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    teacher_id = EXCLUDED.teacher_id;

INSERT INTO enrollments (student_id, course_id) VALUES
    (2, 1),
    (2, 2)
ON CONFLICT DO NOTHING;

INSERT INTO lessons (id, course_id, title, content) VALUES
    (1, 1, 'Урок 1. Переменные и типы данных', 'В C++ переменная связывает имя с областью памяти, где хранится значение определённого типа. Тип определяет, какие значения допустимы и какие операции можно выполнять.\n\nБазовые типы:\n- int для целых чисел;\n- double для вещественных чисел;\n- bool для логических значений;\n- char для одного символа;\n- std::string для строк.\n\nПример:\nint age = 20;\ndouble rating = 4.8;\nbool passed = true;\nstd::string name = "Student";\n\nХорошая практика: выбирайте тип по смыслу данных, задавайте понятные имена и инициализируйте переменные сразу при объявлении.'),
    (2, 1, 'Урок 2. Функции и разбиение программы', 'Функция помогает разделить программу на небольшие понятные блоки. У функции есть тип возвращаемого значения, имя, параметры и тело.\n\nПример:\nint sum(int a, int b) {\n    return a + b;\n}\n\nПочему функции важны:\n- уменьшают дублирование кода;\n- позволяют тестировать отдельные части программы;\n- делают код читаемым;\n- помогают выделить бизнес-логику.\n\nЕсли функция ничего не возвращает, используется тип void. Для входных данных лучше выбирать параметры с понятными именами.'),
    (3, 1, 'Урок 3. Строки и стандартная библиотека', 'Для работы со строками в C++ обычно используется std::string из заголовочного файла <string>. Строки можно объединять, сравнивать, передавать в функции и читать из ввода.\n\nПример:\n#include <string>\n\nstd::string firstName = "Daniil";\nstd::string greeting = "Hello, " + firstName;\n\nСтандартная библиотека C++ экономит время: в ней уже есть контейнеры, алгоритмы, строки и инструменты ввода-вывода. На практике важно не писать всё с нуля, а грамотно использовать готовые компоненты.'),
    (4, 2, 'Урок 1. Классы и объекты', 'Класс описывает структуру объекта: его данные и поведение. Объект — это конкретный экземпляр класса.\n\nПример:\nclass Course {\npublic:\n    std::string title;\n\n    void printTitle() const {\n        std::cout << title;\n    }\n};\n\nКласс помогает объединить связанные данные и операции. Это делает программу ближе к предметной области: Course, User, Test, Lesson выглядят естественно для LMS.'),
    (5, 2, 'Урок 2. Инкапсуляция', 'Инкапсуляция ограничивает прямой доступ к внутреннему состоянию объекта. Обычно поля делают private, а безопасные операции — public.\n\nЗачем это нужно:\n- объект сам контролирует корректность данных;\n- внешний код меньше зависит от внутренней реализации;\n- проще менять класс без поломки всей системы.\n\nВ LMS примером инкапсуляции может быть сервис попыток теста: внешний код отправляет ответы, а сервис сам считает балл, процент и статус прохождения.'),
    (6, 3, 'Урок 1. SELECT и фильтрация', 'SELECT используется для чтения данных из таблиц. Базовая форма запроса:\n\nSELECT column_name FROM table_name WHERE condition;\n\nПримеры:\nSELECT title FROM courses;\nSELECT login FROM users WHERE role = ''Student'';\n\nWHERE позволяет отфильтровать строки. ORDER BY сортирует результат. LIMIT ограничивает количество строк. Эти операции часто используются в API, когда клиент запрашивает списки курсов, пользователей или попыток.'),
    (7, 3, 'Урок 2. Связи таблиц', 'Реляционная база данных хранит сущности в отдельных таблицах, а связи между ними задаются внешними ключами.\n\nПример LMS:\n- users хранит пользователей;\n- courses хранит курсы;\n- enrollments связывает студентов и курсы;\n- lessons привязаны к courses;\n- tests привязаны к courses.\n\nJOIN позволяет получить данные из нескольких таблиц сразу, например список курсов вместе с ФИО преподавателя.')
ON CONFLICT (id) DO UPDATE SET
    course_id = EXCLUDED.course_id,
    title = EXCLUDED.title,
    content = EXCLUDED.content;

INSERT INTO materials (id, lesson_id, title, type, content) VALUES
    (1, 1, 'Конспект: выбор типа данных', 'text', 'Краткая памятка:\n1. int — счётчики, идентификаторы, количество.\n2. double — дробные значения и измерения.\n3. bool — флаги состояния.\n4. std::string — текстовые данные.\n\nЕсли значение не должно меняться, используйте const. Это делает намерение кода очевидным.'),
    (2, 1, 'Справочник cppreference: fundamental types', 'link', 'https://en.cppreference.com/w/cpp/language/types'),
    (3, 2, 'Практика: разбиение программы на функции', 'text', 'Задание: напишите функции calculateAverage, isPassed и formatStudentResult. Главная функция должна только читать данные, вызывать эти функции и выводить результат.'),
    (4, 2, 'Видео: функции в C++', 'video', 'https://www.youtube.com/results?search_query=c%2B%2B+functions+tutorial'),
    (5, 3, 'Справочник: std::string', 'link', 'https://en.cppreference.com/w/cpp/string/basic_string'),
    (6, 4, 'Шаблон класса Course', 'text', 'Минимальная структура класса Course:\n- поле title;\n- поле description;\n- метод printSummary();\n- конструктор с параметрами.\n\nДополнительно: попробуйте скрыть поля через private и добавить getters.'),
    (7, 5, 'Инкапсуляция на примере LMS', 'text', 'В хорошей архитектуре UI не должен сам считать результат теста. Qt-клиент отправляет ответы, backend проверяет их через сервис и возвращает готовый результат. Это снижает риск ошибок и делает систему надёжнее.'),
    (8, 6, 'Памятка SQL SELECT', 'text', 'SELECT title, description FROM courses ORDER BY id;\nSELECT login, role FROM users WHERE role = ''Teacher'';\nSELECT * FROM attempts WHERE percentage >= 70;'),
    (9, 7, 'PostgreSQL JOIN documentation', 'link', 'https://www.postgresql.org/docs/current/tutorial-join.html')
ON CONFLICT (id) DO UPDATE SET
    lesson_id = EXCLUDED.lesson_id,
    title = EXCLUDED.title,
    type = EXCLUDED.type,
    content = EXCLUDED.content;

INSERT INTO lesson_progress (user_id, lesson_id, completed_at) VALUES
    (2, 1, CURRENT_TIMESTAMP - INTERVAL '3 days')
ON CONFLICT (user_id, lesson_id) DO NOTHING;

INSERT INTO tests (id, course_id, title) VALUES
    (1, 1, 'C++ Basic Test'),
    (2, 1, 'Functions and Strings Test'),
    (3, 2, 'OOP Principles Test')
ON CONFLICT (id) DO UPDATE SET
    course_id = EXCLUDED.course_id,
    title = EXCLUDED.title;

INSERT INTO questions (id, test_id, text, correct_answer_id) VALUES
    (1, 1, 'Какой тип данных хранит значения true или false?', NULL),
    (2, 1, 'Какой заголовочный файл обычно подключают для std::string?', NULL),
    (3, 1, 'Что означает const перед переменной?', NULL),
    (4, 2, 'Что описывает тип возвращаемого значения функции?', NULL),
    (5, 2, 'Зачем программу разбивают на функции?', NULL),
    (6, 3, 'Какой модификатор доступа чаще используют для скрытия внутреннего состояния класса?', NULL),
    (7, 3, 'Что такое объект в ООП?', NULL)
ON CONFLICT (id) DO UPDATE SET
    test_id = EXCLUDED.test_id,
    text = EXCLUDED.text;

INSERT INTO answers (id, question_id, text) VALUES
    (1, 1, 'int'),
    (2, 1, 'bool'),
    (3, 1, 'double'),
    (4, 1, 'char'),
    (5, 2, '<string>'),
    (6, 2, '<vector>'),
    (7, 2, '<iostream>'),
    (8, 2, '<map>'),
    (9, 3, 'Значение нельзя изменить после инициализации'),
    (10, 3, 'Переменная становится глобальной'),
    (11, 3, 'Тип автоматически меняется во время выполнения'),
    (12, 3, 'Компилятор игнорирует эту переменную'),
    (13, 4, 'Тип значения, которое функция возвращает вызывающему коду'),
    (14, 4, 'Имя функции'),
    (15, 4, 'Количество параметров'),
    (16, 4, 'Файл, где находится функция'),
    (17, 5, 'Чтобы убрать дублирование и сделать код понятнее'),
    (18, 5, 'Чтобы программа обязательно работала медленнее'),
    (19, 5, 'Чтобы все переменные стали глобальными'),
    (20, 5, 'Чтобы не подключать заголовочные файлы'),
    (21, 6, 'private'),
    (22, 6, 'public'),
    (23, 6, 'friend'),
    (24, 6, 'static'),
    (25, 7, 'Конкретный экземпляр класса'),
    (26, 7, 'Только текстовый файл'),
    (27, 7, 'Любая SQL-таблица'),
    (28, 7, 'Оператор ветвления')
ON CONFLICT (id) DO UPDATE SET
    question_id = EXCLUDED.question_id,
    text = EXCLUDED.text;

UPDATE questions SET correct_answer_id = 2 WHERE id = 1;
UPDATE questions SET correct_answer_id = 5 WHERE id = 2;
UPDATE questions SET correct_answer_id = 9 WHERE id = 3;
UPDATE questions SET correct_answer_id = 13 WHERE id = 4;
UPDATE questions SET correct_answer_id = 17 WHERE id = 5;
UPDATE questions SET correct_answer_id = 21 WHERE id = 6;
UPDATE questions SET correct_answer_id = 25 WHERE id = 7;

INSERT INTO attempts (id, user_id, test_id, score, total, percentage, passed, created_at) VALUES
    (1, 2, 1, 2, 3, 66.7, false, CURRENT_TIMESTAMP - INTERVAL '3 days'),
    (2, 2, 2, 2, 2, 100.0, true, CURRENT_TIMESTAMP - INTERVAL '1 day')
ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('users', 'id'), COALESCE((SELECT MAX(id) FROM users), 1));
SELECT setval(pg_get_serial_sequence('courses', 'id'), COALESCE((SELECT MAX(id) FROM courses), 1));
SELECT setval(pg_get_serial_sequence('lessons', 'id'), COALESCE((SELECT MAX(id) FROM lessons), 1));
SELECT setval(pg_get_serial_sequence('materials', 'id'), COALESCE((SELECT MAX(id) FROM materials), 1));
SELECT setval(pg_get_serial_sequence('tests', 'id'), COALESCE((SELECT MAX(id) FROM tests), 1));
SELECT setval(pg_get_serial_sequence('questions', 'id'), COALESCE((SELECT MAX(id) FROM questions), 1));
SELECT setval(pg_get_serial_sequence('answers', 'id'), COALESCE((SELECT MAX(id) FROM answers), 1));
SELECT setval(pg_get_serial_sequence('attempts', 'id'), COALESCE((SELECT MAX(id) FROM attempts), 1));
SELECT setval(pg_get_serial_sequence('admin_audit_log', 'id'), COALESCE((SELECT MAX(id) FROM admin_audit_log), 1));
